services:
  eureka-server:
    container_name: eureka-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - pgsg-network

networks:
  pgsg-network:
    name: pgsg-network
    driver: bridge